export const modules = [
  {
    id: 'foundations', no: '00', title: '进入模型之前', short: '地基', weeks: '2 周', hours: 18,
    summary: '把数学、Python 与张量补到“够用且能解释”的程度；建立实验、记录与复现习惯。',
    question: '一个模型到底在优化什么？数据、参数、损失和梯度如何连起来？',
    color: '#8da89e',
    lessons: [
      ['0.1', '先画地图：LLM 全栈与学习方法', '地图', '45 分钟', '预训练、后训练、推理、应用四层；参数与状态的边界', '画出一次请求从文本到输出 token 的完整链路'],
      ['0.2', 'Python：对象、迭代器与向量化思维', '代码', '90 分钟', '引用语义、广播、切片、生成器与复杂度', '不用循环实现批量 bigram 计数'],
      ['0.3', '线性代数只学模型真正会用的', '理论', '120 分钟', '向量空间、矩阵乘法、基变换、特征值与 SVD 直觉', '用 NumPy 写线性层并追踪所有 shape'],
      ['0.4', '概率、信息量与交叉熵', '理论', '110 分钟', '条件概率、期望、熵、KL 散度、最大似然', '从计数分布推导并计算 NLL'],
      ['0.5', '导数、偏导与链式法则', '推导', '100 分钟', '局部斜率、Jacobian、计算图、向量-雅可比积', '手算一个二层函数的所有局部导数'],
      ['0.6', 'PyTorch 张量与可复现实验', '实验', '120 分钟', 'dtype、device、stride、autograd、随机种子', '建立可复现的 tensor-lab 仓库'],
      ['0.7', '掌握门 0：读懂一条训练循环', '验收', '90 分钟', '数据、前向、损失、反向、更新的闭环', '解释并修复三条故意损坏的训练循环'],
    ],
    project: 'Tensor Field Notes：一份包含 shape、数值稳定性与梯度实验的可复现笔记。',
    mastery: ['能从最大似然推到交叉熵', '看到矩阵运算能说出每一维含义', '能独立读懂并调试基础 PyTorch 训练循环'],
    sources: ['PyTorch Learn the Basics', 'Dive into Deep Learning', '3Blue1Brown · Linear Algebra'],
  },
  {
    id: 'autograd', no: '01', title: '神经网络地基', short: '反向传播', weeks: '3 周', hours: 28,
    summary: '沿着 micrograd 的极简路径，从标量计算图一直走到一个可训练的 MLP。',
    question: '反向传播为什么有效？梯度究竟沿着什么结构、以什么规则流动？',
    color: '#37d6a2',
    lessons: [
      ['1.1', '神经元不是魔法：函数、参数与激活', '直觉', '75 分钟', '线性组合、非线性、表达能力与决策边界', '手工搭一个二输入神经元'],
      ['1.2', '链式法则是一条消息传递规则', '推导', '100 分钟', '局部导数、上游梯度、梯度累加', '给计算图逐边标注梯度'],
      ['1.3', '让梯度沿计算图倒着走', '代码', '120 分钟', '动态 DAG、reverse-mode autodiff、拓扑排序', '实现 Value、运算符与 backward'],
      ['1.4', '梯度检查：相信代码之前先验证', '实验', '80 分钟', '有限差分、中心差分、误差尺度', '对每个运算符做 PyTorch 对拍'],
      ['1.5', '从 Value 到 Neuron、Layer、MLP', '代码', '120 分钟', '参数容器、模块组合、前向图', '用 50 行代码搭 MLP'],
      ['1.6', '损失、正则化与 SGD', '实验', '110 分钟', 'margin loss、batch、weight decay、学习率', '训练 two-moons 分类器并画边界'],
      ['1.7', '为什么网络会训坏', '诊断', '100 分钟', '死 ReLU、梯度消失/爆炸、初始化与激活统计', '诊断四个故障网络'],
      ['1.8', '掌握门 1：闭卷重写 micrograd', '验收', '180 分钟', '从零复现自动微分最小内核', '90 分钟实现 + 60 分钟讲解 + 30 分钟对拍'],
    ],
    project: 'micrograd-cn：带中文可视化、梯度检查和 MLP 演示的微型自动微分引擎。',
    mastery: ['能口述 reverse-mode autodiff 的完整过程', '能解释拓扑排序和梯度累加的必要性', '能定位初始化、梯度与学习率问题'],
    sources: ['Karpathy · micrograd', 'Zero to Hero · Lecture 1', 'PyTorch Autograd'],
  },
  {
    id: 'language', no: '02', title: '语言如何变成概率', short: 'Token 与 LM', weeks: '3 周', hours: 30,
    summary: '从字符计数、bigram、MLP 语言模型走到 BPE tokenizer，理解模型为何只是“预测下一个”。',
    question: '文字如何被变成离散 token？“理解语言”为什么可以写成条件概率？',
    color: '#37d6a2',
    lessons: [
      ['2.1', 'Bigram：最小语言模型', '代码', '100 分钟', '计数、条件分布、采样与平滑', '训练并采样一个姓名生成器'],
      ['2.2', '负对数似然：模型的记分牌', '推导', '90 分钟', 'likelihood、log、NLL、交叉熵', '从概率表手算平均 NLL'],
      ['2.3', 'Embedding：把离散符号放进空间', '理论', '100 分钟', '查表、稠密表示、相似性与上下文窗口', '可视化字符 embedding'],
      ['2.4', 'MLP 语言模型与数据切分', '实验', '120 分钟', 'Bengio LM、train/dev/test、欠拟合与过拟合', '复现 makemore MLP'],
      ['2.5', '训练深网：激活、梯度与 BatchNorm', '诊断', '120 分钟', '初始化尺度、饱和、BatchNorm 训练/推理差异', '建立 activation/gradient dashboard'],
      ['2.6', '手工反传：成为 Backprop Ninja', '推导', '150 分钟', 'cross entropy、tanh、BatchNorm 的张量级反传', '不调用 backward 完成整网反传'],
      ['2.7', 'BPE：从字节到子词', '代码', '140 分钟', 'UTF-8、pair merge、vocabulary、encode/decode', '从零实现 BasicTokenizer'],
      ['2.8', 'Tokenizer 的隐形代价', '实验', '90 分钟', '数字、空格、多语言、特殊 token、压缩率', '比较中英日文本的 tokenization pathology'],
      ['2.9', '掌握门 2：实现 minBPE + makemore', '验收', '180 分钟', '语言建模与 tokenizer 的完整闭环', '未知语料训练、评测并解释失败案例'],
    ],
    project: 'Tiny Language Lab：可训练 tokenizer 与字符/子词语言模型的交互实验台。',
    mastery: ['能从计数模型推到神经语言模型', '能解释交叉熵与困惑度', '能实现 BPE 并分析 tokenizer 对模型行为的影响'],
    sources: ['Karpathy · makemore', 'Karpathy · minbpe', 'Zero to Hero · Lectures 2–6, 8'],
  },
  {
    id: 'transformer', no: '03', title: '从注意力到 GPT', short: 'Transformer', weeks: '4 周', hours: 42,
    summary: '逐行实现 self-attention、Transformer block 与 GPT，并复现一个小型 GPT-2 训练。',
    question: '没有循环结构，token 如何读取上下文？GPT 的每一层究竟做了什么？',
    color: '#37d6a2',
    lessons: [
      ['3.1', '上下文聚合：从平均池化到注意力', '直觉', '100 分钟', 'weighted aggregation、query/key/value 的动机', '逐步替换一个 bigram 模型的上下文'],
      ['3.2', 'Scaled Dot-Product Attention', '推导', '120 分钟', '相似度、缩放、mask、softmax、shape', 'NumPy 手写单头注意力'],
      ['3.3', 'Multi-Head：并行读取不同关系', '代码', '100 分钟', 'head 分割、concat、projection、容量', '实现并可视化多头注意力'],
      ['3.4', '位置、残差与归一化', '理论', '110 分钟', 'positional embedding、pre-norm、residual stream', '比较 pre/post norm 的梯度'],
      ['3.5', 'Transformer Block 逐行实现', '代码', '140 分钟', 'attention、MLP、dropout、LayerNorm 组合', '写出可单测的 Block'],
      ['3.6', 'GPT：自回归目标与权重共享', '代码', '150 分钟', 'causal LM、embedding tying、logits、generation', '从零完成 miniGPT'],
      ['3.7', '采样不是随机按钮', '实验', '100 分钟', 'temperature、top-k、top-p、repetition', '建立采样参数相图'],
      ['3.8', '读懂 GPT-2：配置、参数量、权重加载', '工程', '120 分钟', '模型配置、state_dict、权重转置', '加载官方 GPT-2 权重对齐 logits'],
      ['3.9', '复现 124M：从正确到更快', '工程', '180 分钟', 'mixed precision、compile、FlashAttention、梯度累积', '沿 Karpathy 视频逐项优化吞吐'],
      ['3.10', '掌握门 3：闭卷画出并实现 GPT', '验收', '240 分钟', '架构、目标、训练与生成统一', '白板推导 + 最小实现 + 新语料训练报告'],
    ],
    project: 'nanoGPT Studio：训练一个 10–30M 参数中文专题模型，附 loss 曲线、消融与 model card。',
    mastery: ['能标出 Transformer 每个张量的 shape', '能解释 mask、缩放、残差与归一化', '能从零实现并训练一个 decoder-only GPT'],
    sources: ['Karpathy · nanoGPT', 'Let’s build GPT', 'Let’s reproduce GPT-2', 'Attention Is All You Need'],
  },
  {
    id: 'training', no: '04', title: '把训练变成系统', short: '数据与规模化', weeks: '4 周', hours: 44,
    summary: '从单卡训练循环深入到数据工程、性能核算、并行策略、Scaling Laws 与稳定性。',
    question: '模型能跑和训练得好之间，隔着哪些数据、硬件与系统问题？',
    color: '#37d6a2',
    lessons: [
      ['4.1', '训练前先算账：参数、FLOPs 与显存', '推导', '110 分钟', '参数量、activation memory、optimizer states、MFU', '为 7B 模型做资源预算表'],
      ['4.2', '数据工程：采集、清洗、去重与混合', '工程', '140 分钟', 'quality filtering、MinHash、contamination、mixture', '构建 1GB 可追溯小语料'],
      ['4.3', '训练循环的每一个旋钮', '实验', '120 分钟', 'AdamW、warmup、cosine、clip、checkpoint', '做优化器与学习率消融'],
      ['4.4', '混合精度与数值稳定性', '诊断', '110 分钟', 'FP32/FP16/BF16、loss scaling、overflow', '复现并修复 NaN 训练'],
      ['4.5', 'GPU、Kernel 与内存层级', '系统', '140 分钟', 'HBM、SRAM、arithmetic intensity、roofline', 'profile attention 算子'],
      ['4.6', 'FlashAttention 与 Triton 入门', '代码', '180 分钟', 'IO-aware tiling、online softmax、kernel fusion', '实现简化 fused softmax'],
      ['4.7', '并行训练：DP、TP、PP、FSDP', '系统', '170 分钟', '通信拓扑、all-reduce、shard、bubble', '为不同集群选择并行策略'],
      ['4.8', 'Scaling Laws 与 Chinchilla 直觉', '理论', '100 分钟', 'compute-optimal、数据/参数配比、外推风险', '拟合一组小模型 scaling curve'],
      ['4.9', '训练可观测性与故障恢复', '工程', '120 分钟', 'loss spike、straggler、checkpoint、数据漂移', '设计训练 runbook'],
      ['4.10', '掌握门 4：从 nanoGPT 到小型预训练', '验收', '240 分钟', '数据、资源、训练、评估统一', '提交预算、日志、故障复盘与可复现实验'],
    ],
    project: 'Pretrain Runbook：一次 10M–100M 模型预训练的完整工程档案。',
    mastery: ['能估算训练所需算力与显存', '能解释训练性能瓶颈与并行策略', '能建立可恢复、可诊断的训练流水线'],
    sources: ['Stanford CS336', 'Karpathy · llm.c', 'Megatron-LM', 'PyTorch Distributed'],
  },
  {
    id: 'alignment', no: '05', title: '让模型成为助手', short: '后训练与评测', weeks: '4 周', hours: 40,
    summary: '理解 base model 到 assistant 的跃迁：SFT、偏好优化、RL、评测、安全与可解释性。',
    question: '预测下一个 token 的模型，如何学会遵循意图、使用工具并拒绝危险请求？',
    color: '#37d6a2',
    lessons: [
      ['5.1', 'Base model 与 Assistant 的断层', '直觉', '80 分钟', '预训练分布、对话模板、行为塑形', '比较 base/instruct 输出分布'],
      ['5.2', 'SFT：用示范重写行为先验', '工程', '130 分钟', 'instruction data、mask、packing、chat template', '用 LoRA 做一次小型 SFT'],
      ['5.3', '偏好数据与奖励模型', '理论', '120 分钟', 'pairwise preference、Bradley-Terry、reward hacking', '训练微型 reward model'],
      ['5.4', 'DPO：绕开奖励模型的偏好优化', '推导', '120 分钟', 'reference policy、KL、DPO objective', '从公式实现 DPO loss'],
      ['5.5', 'PPO / GRPO 与 RL 后训练', '理论', '150 分钟', 'policy gradient、advantage、KL control、rollout', '在玩具任务比较 SFT/DPO/RL'],
      ['5.6', '评测：先定义“好”再优化', '工程', '140 分钟', 'perplexity、task eval、LLM judge、污染与方差', '建立最小 eval harness'],
      ['5.7', '幻觉、校准与不确定性', '诊断', '100 分钟', '事实性、abstention、confidence、RAG 边界', '设计可证伪的幻觉评测集'],
      ['5.8', '安全、红队与系统卡', '工程', '110 分钟', 'threat model、jailbreak、misuse、risk register', '完成一次小模型红队'],
      ['5.9', '从激活看内部：可解释性入口', '理论', '100 分钟', 'probing、activation patching、circuits、SAE 直觉', '用 TransformerLens 做一次 patching'],
      ['5.10', '掌握门 5：后训练方案答辩', '验收', '210 分钟', '目标、数据、算法、评测、安全闭环', '为一个客服模型设计并答辩完整方案'],
    ],
    project: 'Aligned Mini-Assistant：SFT + DPO + eval + system card 的可复现小型助手。',
    mastery: ['能推导 SFT、DPO 与 policy gradient 的目标差异', '能识别评测污染和 LLM-as-judge 风险', '能建立数据—训练—评测—安全闭环'],
    sources: ['Karpathy · Deep Dive into LLMs', 'Hugging Face TRL', 'lm-evaluation-harness', 'Transformer Circuits'],
  },
  {
    id: 'inference', no: '06', title: '让模型快而可靠地说话', short: '推理与部署', weeks: '3 周', hours: 30,
    summary: '深入 KV Cache、量化、批处理与服务架构，分别跑通本地端和 GPU 服务端。',
    question: '训练完成只是起点：怎样把每个 token 更快、更省、更稳定地交付给用户？',
    color: '#37d6a2',
    lessons: [
      ['6.1', 'Prefill 与 Decode：两种完全不同的负载', '系统', '90 分钟', 'compute-bound、memory-bound、latency、throughput', 'profile 一次完整生成'],
      ['6.2', 'KV Cache：用显存换重复计算', '推导', '100 分钟', 'cache shape、容量、GQA/MQA、长上下文', '手写带 cache 的 attention'],
      ['6.3', '量化：数值、误差与校准', '理论', '120 分钟', 'INT8/INT4、weight-only、GPTQ/AWQ/GGUF', '对比 4 种量化的质量和速度'],
      ['6.4', 'llama.cpp：本地推理的工程解剖', '工程', '130 分钟', 'GGUF、mmap、CPU/GPU offload、sampling', '在 Mac 上部署并 benchmark'],
      ['6.5', 'vLLM：PagedAttention 与连续批处理', '系统', '130 分钟', 'block table、continuous batching、scheduler', '搭建 OpenAI-compatible 服务'],
      ['6.6', '服务可靠性：限流、缓存、降级与观测', '工程', '120 分钟', 'SLO、queue、backpressure、prefix cache、tracing', '为 100 QPS 设计容量方案'],
      ['6.7', '掌握门 6：两套部署、一份基准', '验收', '180 分钟', '端侧与服务端方案对比', '提交延迟、吞吐、成本、质量与故障注入报告'],
    ],
    project: 'Inference Bench：llama.cpp + vLLM 双后端基准站，自动生成性能/质量报告。',
    mastery: ['能解释 prefill/decode 与 KV Cache', '能选择合理量化与批处理策略', '能以 SLO 驱动部署和容量设计'],
    sources: ['llama.cpp', 'vLLM', 'DeepSeek · DeepSpec / DSpark', 'Stanford CS336 · Inference'],
  },
  {
    id: 'agents', no: '07', title: '从模型到智能系统', short: 'Agent 与毕业作', weeks: '3 周', hours: 32,
    summary: '不把 Agent 当框架 API：从状态机、工具协议、记忆、规划与评测搭出可靠系统。',
    question: '一个会生成文本的模型，何时才能成为可观察、可控制、可验证的执行系统？',
    color: '#37d6a2',
    lessons: [
      ['7.1', 'Agent 的最小闭环', '直觉', '90 分钟', 'observe–reason–act、environment、termination', '不用框架写一个 tool loop'],
      ['7.2', '工具调用与结构化输出', '工程', '110 分钟', 'schema、validation、idempotency、side effect', '实现带重试的安全工具层'],
      ['7.3', '上下文工程与记忆', '系统', '120 分钟', 'working context、retrieval、summary、memory policy', '比较三种记忆策略'],
      ['7.4', '规划、反思与多 Agent', '理论', '120 分钟', 'decomposition、search、critic、coordination cost', '在可验证任务上做消融'],
      ['7.5', 'Agent 评测：从最终答案到轨迹', '工程', '130 分钟', 'task success、trajectory、tool error、cost、latency', '建立 30 条回归任务集'],
      ['7.6', '生产边界：权限、安全与人机协同', '工程', '110 分钟', 'least privilege、approval、sandbox、audit', '为高风险工具做威胁模型'],
      ['7.7', 'nanochat：看懂一套完整聊天系统', '研读', '150 分钟', 'tokenizer、pretrain、midtrain、SFT、RL、UI', '画出 repo 的端到端依赖图'],
      ['7.8', '掌握门 7：毕业答辩', '验收', '240 分钟', '模型原理、训练、部署、系统设计统一', '现场演示、故障注入、技术答辩与复现审查'],
    ],
    project: '毕业作品：一个可公开部署的垂直领域助手，附模型卡、系统卡、eval、成本与复现脚本。',
    mastery: ['能不用框架解释并实现 Agent 循环', '能对轨迹、工具和结果分层评测', '能把模型能力、安全边界与产品 SLO 放进同一设计'],
    sources: ['Karpathy · nanochat', 'Lilian Weng · LLM Agents', 'Hugging Face Agents Course', 'Anthropic · Building Effective Agents'],
  },
  {
    id: 'frontier-llm', no: '08', title: '前沿大模型系统', short: '2025–2026 前沿', weeks: '3 周', hours: 28,
    summary: '把推理模型、稀疏架构、长上下文和新型解码放回可验证的原理与系统约束，而不是追逐模型榜单。',
    question: '近两年的能力跃迁，分别来自架构、数据、后训练、测试时计算和服务系统中的哪一层？',
    color: '#ffb86b',
    lessons: [
      ['8.1', 'MoE、MLA 与多 Token 预测', '研读', '150 分钟', 'Mixture-of-Experts、routing、load balance、MLA、multi-token prediction', '拆解 DeepSeek-V3 的激活参数、KV 压缩与训练目标'],
      ['8.2', '推理模型与可验证奖励强化学习', '理论', '150 分钟', 'RLVR、GRPO、outcome reward、reasoning trace、test-time compute', '复现小模型在可验证任务上的推理 RL 实验'],
      ['8.3', '长上下文不是一个数字', '诊断', '120 分钟', 'sparse attention、retrieval、position、context rot、needle与结构化评测', '建立从检索到多跳推理的分层长上下文评测'],
      ['8.4', 'DSpark：投机解码的生成与调度', '系统', '160 分钟', 'parallel drafter、semi-autoregressive head、prefix survival、hardware-aware scheduling', '实现前缀存活调度器并模拟轻载与高并发'],
      ['8.5', '扩散与块并行语言模型', '理论', '130 分钟', 'masked diffusion、parallel decoding、block diffusion、quality-speed trade-off', '比较自回归、并行草稿与扩散草稿的时延模型'],
      ['8.6', '面向 Agent 的后训练', '工程', '150 分钟', 'tool-use trajectory、task synthesis、verifiable environment、process与outcome reward', '为工具型 Agent 设计可回放的训练与评测数据管线'],
    ],
    project: 'Frontier Systems Review：选择一个前沿方案，用复现实验、成本模型和失败案例判断它解决了哪一层问题。',
    mastery: ['能把模型能力提升归因到具体技术层而非品牌', '能区分离线 benchmark、单用户速度与生产吞吐', '能审计推理、长上下文和 Agent 评测中的污染与代理指标'],
    sources: ['DeepSeek-V3 / V3.2 / R1', 'DeepSeek · DSpark', 'Stanford CS336 · 2025–2026 materials'],
  },
]

export const resources = [
  { author: 'Andrej Karpathy', title: 'Neural Networks: Zero to Hero', type: '课程', level: '主线', phase: '地基 → GPT', url: 'https://karpathy.ai/zero-to-hero.html', note: '本课程的第一性原理主轴；不要只看，逐行复现并完成练习。' },
  { author: 'Andrej Karpathy', title: 'micrograd', type: '代码', level: '必做', phase: '反向传播', url: 'https://github.com/karpathy/micrograd', note: '约百行标量自动微分内核，是理解 autograd 的最佳切口。' },
  { author: 'Andrej Karpathy', title: 'makemore', type: '代码', level: '必做', phase: '语言模型', url: 'https://github.com/karpathy/makemore', note: '从 bigram 到 Transformer 的自回归字符模型演化。' },
  { author: 'Andrej Karpathy', title: 'minbpe', type: '代码', level: '必做', phase: 'Tokenizer', url: 'https://github.com/karpathy/minbpe', note: '干净、最小的 BPE 实现；配合 tokenizer 视频学习。' },
  { author: 'Andrej Karpathy', title: 'nanoGPT', type: '代码', level: '必做', phase: 'GPT / 训练', url: 'https://github.com/karpathy/nanoGPT', note: '理解 GPT 训练骨架，之后再进入更大型框架。' },
  { author: 'Andrej Karpathy', title: 'Let’s reproduce GPT-2 (124M)', type: '视频', level: '主线', phase: 'GPT / 性能', url: 'https://www.youtube.com/watch?v=l8pRSuU81PU', note: '从正确实现一路优化到接近生产训练循环。' },
  { author: 'Andrej Karpathy', title: 'llm.c', type: '代码', level: '进阶', phase: '训练系统', url: 'https://github.com/karpathy/llm.c', note: '绕开高层抽象，在 C/CUDA 里看清训练的真实成本。' },
  { author: 'Andrej Karpathy', title: 'Deep Dive into LLMs like ChatGPT', type: '视频', level: '主线', phase: '全局 / 后训练', url: 'https://www.youtube.com/watch?v=7xTGNNLPyMI', note: '建立从 tokenizer、预训练到后训练的完整心智模型。' },
  { author: 'Andrej Karpathy', title: 'A Recipe for Training Neural Networks', type: '博客', level: '必读', phase: '训练诊断', url: 'https://karpathy.github.io/2019/04/25/recipe/', note: '把“先让模型过拟合一个 batch”等工程纪律变成训练检查表。' },
  { author: 'Andrej Karpathy', title: 'Yes, you should understand backprop', type: '博客', level: '必读', phase: '反向传播', url: 'https://karpathy.medium.com/yes-you-should-understand-backprop-e2f06eab496b', note: '理解反向传播为何是“会漏的抽象”，并把反直觉失败案例变成诊断意识。' },
  { author: 'Andrej Karpathy', title: 'Hacker’s Guide to Neural Networks', type: '博客', level: '补强', phase: '神经网络地基', url: 'https://karpathy.github.io/neuralnets/', note: '少公式、多代码的早期教程，与 micrograd 路线形成很好的互证。' },
  { author: 'Andrej Karpathy', title: 'The Unreasonable Effectiveness of RNNs', type: '博客', level: '选读', phase: '序列模型', url: 'https://karpathy.github.io/2015/05/21/rnn-effectiveness/', note: '以字符 RNN 建立序列建模直觉，也能看清 Transformer 改进了什么。' },
  { author: 'Andrej Karpathy', title: 'Software 2.0', type: '博客', level: '视野', phase: '数据与系统', url: 'https://karpathy.medium.com/software-2-0-a64152b37c35', note: '理解数据、训练和评测为什么成为新型软件工程的核心资产。' },
  { author: 'Andrej Karpathy', title: 'nanochat', type: '代码', level: '毕业研读', phase: '完整系统', url: 'https://github.com/karpathy/nanochat', note: '把 tokenizer、预训练、后训练、评测与聊天 UI 串成一个端到端系统。' },
  { author: 'Andrej Karpathy', title: 'LLM101n · Storyteller 蓝图', type: '课程', level: '路线蓝图', phase: '端到端', url: 'https://github.com/karpathy/LLM101n', note: '17 章端到端课程蓝图；项目已归档、课程尚未正式发布，适合用来核对知识覆盖面。' },
  { author: 'Andrej Karpathy', title: '@karpathy on X', type: '动态', level: '趋势雷达', phase: '最新实验', url: 'https://x.com/karpathy', note: '只在完成主线后追踪 nanochat、autoresearch 与训练实验更新，避免碎片化学习。' },
  { author: 'Andrej Karpathy', title: 'How I use LLMs', type: '视频', level: '应用线', phase: '模型使用', url: 'https://www.youtube.com/watch?v=EWvNQjAaOHw', note: '从使用者视角理解模型能力边界、工具协作与人机交互模式。' },
  { author: '跟李沐学AI', title: 'Transformer 论文逐段精读', type: '视频', level: '中文深读', phase: '注意力 / Transformer', url: 'https://www.bilibili.com/video/BV1pu411o7BE', note: '结合原论文逐段理解缩放点积注意力、多头结构、位置编码与训练设计。' },
  { author: '跟李沐学AI', title: 'Llama 3.1 论文精读系列', type: '视频', level: '工程补强', phase: '数据 / 训练系统', url: 'https://www.bilibili.com/video/BV1WM4m1y7Uh', note: '从预训练数据、模型结构、训练基础设施和训练过程理解现代开放大模型工程。' },
  { author: 'Andrej Karpathy · 社区字幕', title: 'Zero to Hero 中英字幕分P版', type: '视频', level: '国内镜像', phase: '反向传播 → GPT-2', url: 'https://www.bilibili.com/video/BV1mqrTBvEaf', note: '按课程章节精确定位分P；属于社区字幕镜像，网站同时保留 Karpathy 原始课程入口。' },
  { author: 'Sebastian Raschka · 社区中配', title: 'Build an LLM From Scratch 配套视频', type: '视频', level: '中文伴学', phase: 'Tokenizer → SFT', url: 'https://www.bilibili.com/video/BV1RpwzzoErr', note: '47 个短分P与书籍章节对应，适合在实现前建立局部机制直觉。' },
  { author: 'Stanford CS336 · 社区字幕', title: 'Language Modeling from Scratch 完整课程', type: '视频', level: '进阶镜像', phase: '训练全栈', url: 'https://www.bilibili.com/video/BV1Ect2zjEHR', note: '覆盖 Tokenizer、架构、GPU、并行、Scaling、数据、评测与 RL；结论以 Stanford 讲义为准。' },
  { author: '3Blue1Brown', title: 'GPT 是什么？直观解释 Transformer', type: '视频', level: '官方双语', phase: '注意力 / GPT', url: 'https://www.bilibili.com/video/BV13z421U7cs', note: '官方账号发布的高质量可视化入口，用于在公式与代码前建立信息流直觉。' },
  { author: 'RethinkFun', title: 'vLLM、KV Cache 与 PagedAttention', type: '视频', level: '中文原创', phase: '推理系统', url: 'https://www.bilibili.com/video/BV1kx4y1x7bu', note: '12 分钟建立核心机制地图，再回到论文、源码和课程实验验证。' },
  { author: '比飞鸟贵重的多_HKL', title: 'llama.cpp 源码逐行调试带读', type: '视频', level: '源码研读', phase: '本地推理', url: 'https://www.bilibili.com/video/BV1N4wreWE8z', note: '22 个分P覆盖 GGUF、后端、内存、KV Cache、计算图与调度器。' },
  { author: 'Stanford', title: 'CS336: Language Modeling from Scratch', type: '课程', level: '进阶主线', phase: '训练全栈', url: 'https://cs336.stanford.edu/', note: '从 tokenizer、架构、系统到数据、Scaling Law、对齐与评测的硬核进阶。' },
  { author: 'PyTorch', title: 'Learn the Basics + Distributed Tutorials', type: '文档', level: '工具线', phase: '框架 / 分布式', url: 'https://docs.pytorch.org/tutorials/', note: '只在理解原理后补齐官方 API 与分布式工程路径。' },
  { author: 'Hugging Face', title: 'LLM Course', type: '课程', level: '工具线', phase: '生态 / 微调', url: 'https://huggingface.co/learn/llm-course/chapter1/1', note: '学习 Transformers、Datasets、Tokenizers 与 Hub 的标准工程方式。' },
  { author: 'Hugging Face', title: 'TRL', type: '代码', level: '进阶', phase: '后训练', url: 'https://huggingface.co/docs/trl/index', note: 'SFT、DPO、PPO/GRPO 等后训练实践入口。' },
  { author: 'Full Stack Deep Learning', title: 'LLM Bootcamp', type: '课程', level: '应用线', phase: 'LLMOps / 产品', url: 'https://fullstackdeeplearning.com/llm-bootcamp/', note: '补齐 prompt、增强、LLMOps、UX 与落地评估。' },
  { author: 'NVIDIA', title: 'Megatron-LM', type: '代码', level: '高级', phase: '规模化训练', url: 'https://github.com/NVIDIA/Megatron-LM', note: '理解张量、流水线、上下文和专家并行的生产实现。' },
  { author: 'ggml-org', title: 'llama.cpp', type: '代码', level: '工程', phase: '本地推理', url: 'https://github.com/ggml-org/llama.cpp', note: 'GGUF、量化、mmap 与异构 offload 的最佳实践场。' },
  { author: 'vLLM Project', title: 'vLLM', type: '代码', level: '工程', phase: '服务推理', url: 'https://docs.vllm.ai/en/latest/', note: '从 PagedAttention 理解高吞吐 LLM serving。' },
  { author: 'DeepSeek-AI', title: 'DeepSpec / DSpark', type: '研究', level: '前沿', phase: '投机解码', url: 'https://github.com/deepseek-ai/DeepSpec', note: '从并行草稿、块内依赖、置信度调度与硬件负载理解生产级投机解码。' },
  { author: 'EleutherAI', title: 'lm-evaluation-harness', type: '代码', level: '工程', phase: '评测', url: 'https://github.com/EleutherAI/lm-evaluation-harness', note: '建立可复现的任务评测与 benchmark 管理方式。' },
  { author: 'Anthropic', title: 'Transformer Circuits', type: '研究', level: '高级', phase: '可解释性', url: 'https://transformer-circuits.pub/', note: '进入特征、回路、superposition 与机制可解释性。' },
  { author: 'Lilian Weng', title: 'LLM Powered Autonomous Agents', type: '博客', level: '必读', phase: 'Agent', url: 'https://lilianweng.github.io/posts/2023-06-23-agent/', note: '把规划、记忆、工具与反思组织成清晰的 Agent 心智模型。' },
  { author: 'Sebastian Raschka', title: 'LLMs from Scratch', type: '代码', level: '补强', phase: 'GPT / 微调', url: 'https://github.com/rasbt/LLMs-from-scratch', note: '另一条非常完整的可执行实现路线，用于交叉验证理解。' },
  { author: 'ARENA', title: 'ARENA 3.0 Curriculum', type: '课程', level: '高级', phase: 'Transformer / RL / MI', url: 'https://github.com/callummcdougall/ARENA_3.0', note: '高质量练习驱动课程，适合模型实现、RL 与可解释性进阶。' },
  { author: 'DeepSeek-AI', title: 'DeepSeek-V3 Technical Report', type: '研究', level: '前沿主线', phase: 'MoE / MLA / MTP', url: 'https://arxiv.org/abs/2412.19437', note: '系统理解专家路由、MLA、无辅助损失负载均衡、FP8 训练与多 Token 预测。' },
  { author: 'DeepSeek-AI', title: 'DeepSeek-R1', type: '研究', level: '前沿主线', phase: '推理 / RLVR', url: 'https://arxiv.org/abs/2501.12948', note: '研究可验证奖励、GRPO、推理行为涌现与蒸馏，同时审计其适用边界。' },
  { author: 'DeepSeek-AI', title: 'DeepSeek-V3.2', type: '研究', level: '前沿', phase: '稀疏注意力 / Agent', url: 'https://arxiv.org/abs/2512.02556', note: '把稀疏注意力、可扩展 RL 和 Agent 任务合成放在同一系统中分析。' },
  { author: 'DeepSeek-AI', title: 'DSpark: Confidence-Scheduled Speculative Decoding', type: '研究', level: '2026 新增', phase: '投机解码', url: 'https://arxiv.org/abs/2607.05147', note: '重点学习半自回归草稿、前缀存活概率和硬件感知验证调度，而非只记速度数字。' },
  { author: 'DFlash authors', title: 'DFlash: Block Diffusion for Flash Speculative Decoding', type: '研究', level: '2026 新增', phase: '扩散草稿', url: 'https://arxiv.org/abs/2602.06036', note: '理解块扩散如何作为并行 drafter，并与自回归解码保持质量—速度对照。' },
]

export const sourceTypes = ['全部', '课程', '视频', '博客', '代码', '文档', '研究', '动态']

export const principles = [
  ['先造最小件', '每个概念先在 50–200 行代码里出现，再进入成熟框架。'],
  ['预测再运行', '每次实验先写下预测；结果偏离时，学习才真正发生。'],
  ['三种证据', '掌握必须同时通过：能解释、能实现、能迁移。'],
  ['公开可复现', '每阶段产出 README、实验日志、测试、结论与失败复盘。'],
]
